# .woodpecker.yml
pipeline:
  build_and_test:
    image: rust:latest
    environment:
      - CARGO_TERM_COLOR=always
    commands:
      - rustup component add clippy rustfmt
      - cargo fmt --all -- --check
      - cargo clippy --all-targets --all-features -- -D warnings
      - cargo test --workspace --all-targets
      - cargo build --workspace --release
