

pipeline:
  setup:
    image: debian:bookworm-slim
    commands:
      - apt-get update && apt-get install -y curl build-essential git
      - curl https://sh.rustup.rs -sSf | sh -s -- -y
      - source $HOME/.cargo/env
      - rustc --version
      - cargo --version

  build:
    image: rust:latest
    commands:
      - cargo build --verbose

  test:
    image: rust:latest
    commands:
      - cargo test --verbose
