name: Rust Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: docker
    container:
      image: rust:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        run: |
          rustup component add clippy rustfmt

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Lint (clippy)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --workspace --all-targets --all-features

      - name: Build (Release)
        run: cargo build --workspace --release
