name: Rust Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: docker
    container:
      image: rust:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4    

      - name: Setup Rust
        run: rustup component add clippy rustfmt

      - name: Build + Test
        run: |
          cargo fmt --all -- --check
          cargo clippy --workspace --all-targets --all-features -- -D warnings
          cargo test --workspace --all-targets
          cargo build --workspace --release
