name: Rust Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: docker
    container:
      image: rust:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Show repo info
        run: |
          echo "Repository checked out successfully"
          echo "Current dir:" $(pwd)
          echo "Contents:"
          ls -la
          
      - name: Setup Rust
        run: rustup component add clippy rustfmt
        
      - name: Build & Test
        working-directory: flare
        run: |
          cargo fmt --all -- --check
          cargo clippy --workspace --all-targets --all-features -- -D warnings
          cargo test --workspace --all-targets
          cargo build --workspace --release