name: Rust Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: docker
    container:
      image: rust:latest
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4
        run: ls -la

      
       
    