name: Rust Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: list directory contents
        run: cargo run

      
       
    