name: Rust Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Install rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Build project
        run: |
          source $HOME/.cargo/env
          cargo build --release


      
       
    