name: Rust Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: docker
    container:
      image: rust:latest
    steps:
      - name: Install Node.js (required for actions)
        run: |
          apt-get update
          apt-get install -y nodejs
          
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Show repo structure
        run: |
          echo "Current dir:" $(pwd)
          echo "Contents of root:"
          ls -la
          echo "Looking for flare directory:"
          find . -name "flare" -type d
          
      - name: Setup Rust
        run: rustup component add clippy rustfmt
        
      - name: Build & Test
        run: |
          cd flare  # Manual cd instead of working-directory
          cargo fmt --all -- --check
          cargo clippy --workspace --all-targets --all-features -- -D warnings
          cargo test --workspace --all-targets
          cargo build --workspace --release